<?php
return array (
  'swm3u8' => 
  array (
    'status' => '1',
    'from' => 'swm3u8',
    'show' => '丝袜在线',
    'des' => '支持手机电脑在线播放',
    'ps' => '1',
    'parse' => 'https://help.siwazyw.com/m3u8.php?url=',
    'sort' => '976',
    'tip' => '无需安装任何插件',
    'id' => 'swm3u8',
  ),
  'dplayer' => 
  array (
    'status' => '1',
    'from' => 'dplayer',
    'show' => 'DPlayer-H5播放器',
    'des' => 'dplayer.js.org',
    'target' => '_self',
    'ps' => '1',
    'parse' => '',
    'sort' => '908',
    'tip' => '无需安装任何插件',
    'id' => 'dplayer',
  ),
  'videojs' => 
  array (
    'status' => '1',
    'from' => 'videojs',
    'show' => 'videojs-H5播放器',
    'des' => 'videojs.com',
    'target' => '_self',
    'ps' => '1',
    'parse' => '',
    'sort' => '907',
    'tip' => '无需安装任何插件',
    'id' => 'videojs',
  ),
  'iva' => 
  array (
    'status' => '1',
    'from' => 'iva',
    'show' => 'iva-H5播放器',
    'des' => 'videojj.com',
    'target' => '_self',
    'ps' => '1',
    'parse' => '',
    'sort' => '906',
    'tip' => '无需安装任何插件',
    'id' => 'iva',
  ),
  'iframe' => 
  array (
    'status' => '1',
    'from' => 'iframe',
    'show' => 'iframe外链数据',
    'des' => 'iframe外链数据',
    'target' => '_self',
    'ps' => '1',
    'parse' => '',
    'sort' => '905',
    'tip' => '无需安装任何插件',
    'id' => 'iframe',
  ),
  'link' => 
  array (
    'status' => '1',
    'from' => 'link',
    'show' => '外链数据',
    'des' => '外部网站播放链接',
    'target' => '_self',
    'ps' => '1',
    'parse' => '',
    'sort' => '904',
    'tip' => '无需安装任何插件',
    'id' => 'link',
  ),
  'swf' => 
  array (
    'status' => '1',
    'from' => 'swf',
    'show' => 'Flash文件',
    'des' => 'swf',
    'target' => '_self',
    'ps' => '1',
    'parse' => '',
    'sort' => '903',
    'tip' => '无需安装任何插件',
    'id' => 'swf',
  ),
  'flv' => 
  array (
    'status' => '1',
    'from' => 'flv',
    'show' => 'Flv文件',
    'des' => 'flv',
    'target' => '_self',
    'ps' => '1',
    'parse' => '',
    'sort' => '902',
    'tip' => '无需安装任何插件	',
    'id' => 'flv',
  ),
  '' => 
  array (
    'status' => '1',
    'from' => '',
    'show' => 'dbm3u8',
    'des' => '百度雲資源',
    'target' => '_self',
    'ps' => '1',
    'parse' => '',
    'sort' => '',
    'tip' => '',
  ),
  'dbm3u8' => 
  array (
    'status' => '1',
    'from' => 'dbm3u8',
    'show' => '百度雲資源',
    'des' => '百度雲資源',
    'target' => '_self',
    'ps' => '1',
    'parse' => '',
    'sort' => '',
    'tip' => '',
  ),
  'MDYM' => 
  array (
    'status' => '1',
    'from' => 'MDYM',
    'show' => '麻豆 源码',
    'des' => 'madouym.com',
    'target' => '_self',
    'ps' => '1',
    'parse' => '',
    'sort' => '',
    'tip' => '',
    'id' => 'MDYM',
  ),
  'lym3u8' => 
  array (
    'status' => '1',
    'from' => 'lym3u8',
    'show' => '老鴨',
    'des' => '老鴨',
    'target' => '_self',
    'ps' => '1',
    'parse' => 'https://player.77lehuo.com/aliplayer/?url=',
    'sort' => '',
    'tip' => '',
    'id' => 'lym3u8',
  ),
);